### ISSUE TITLE
Route file is not generating

### ISSUE THREAD

**Issue by radhareddy31** [rohit-gohri/trafficRL#10]
Dear Rohit, I am trying your updated code. The route file is not generating. Any suggestions why it is happening?

**Comment by rohit-gohri** [comment]
Was because of reorg of some files in sumo tools: https://github.com/eclipse/sumo/issues/1425

**Comment by rohit-gohri** [comment]
Also I noticed that our fork of randomTrips.py is pretty different from the latest SUMO implementation now

**Comment by radhareddy31** [comment]
Many thanks Rohit. Any suggestions to solve this issue?

**Comment by rohit-gohri** [comment]
I fixed it, if you could pull the latest code route file should generate now.

As for randomTrips, you can use the official one that option was always there. I was just pointing it out that the logic is different than the one described here: https://sumo.dlr.de/docs/Tools/Trip.html

**Comment by radhareddy31** [comment]
Thanks Rohit, but still it is not generating the route file with the following error, **Error: The route file 'data/cross.rou.xml' is not accessible.
Quitting (on error).**
