### ISSUE TITLE
Regarding the documentation/papers

### ISSUE THREAD

**Issue by radhareddy31** [rohit-gohri/trafficRL#6]
Dear Rohit,

Is there any documentation/papers/thesis on this trafficRL Project?

Will you please share them if possible!

Regards
Radha

**Comment by rohit-gohri** [comment]
Hi, 

Yes, my friend @arorashu uploaded it now. Please find it in the main repo: https://github.com/arorashu/trafficRL/blob/master/thesis_report_Adaptive_Traffic_Light_Control_RL.pdf
